# Site settings
title: The Bay Easy Brass Band
email: jonathan@jonathanbayer.com
description: > # this means to ignore newlines until "baseurl:"
  For the best New Orleans music the Bay Area has to offer.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://bayeasybrassband.com" # the base hostname & protocol for your site
twitter_username: 
github_username: jonathanbayer

# Build settings
markdown: kramdown
